micronaut:
  application:
    name: test
datasources:
  default:
    url: jdbc:mysql://localhost:3306/chariot
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    schema-generate: CREATE_DROP
    dialect: MYSQL
#flyway:
#  datasources:
#    default:
#      enabled: true
